# Generated by Django 5.0.2 on 2024-02-28 05:57

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
