# Generated by Django 5.0.2 on 2024-02-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.TextField(max_length=30)),
                ('reason', models.TextField(max_length=30)),
            ],
        ),
    ]
