# Generated by Django 5.0.2 on 2024-03-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforleave',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
