# Generated by Django 5.0.2 on 2024-03-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_applyforleave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforleave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
