# Generated by Django 5.0.2 on 2024-03-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_applyforleave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforleave',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
