# Generated by Django 5.0.3 on 2024-03-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_applyforleave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforleave',
            name='reject_reason',
            field=models.TextField(default=''),
        ),
    ]
