# Generated by Django 5.0.3 on 2024-03-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_applyforleave_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforleave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
