# Generated by Django 5.0.3 on 2024-03-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_applyforleave_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyforleave',
            name='employee',
        ),
    ]
