# Generated by Django 5.0.3 on 2024-03-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_applyforleave_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
