# Generated by Django 5.0.3 on 2024-04-03 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_remove_applyforleave_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leave', models.IntegerField(default=24)),
                ('approved_days', models.IntegerField(default=0)),
                ('pending_leaves', models.IntegerField(default=24)),
            ],
        ),
        migrations.AlterField(
            model_name='applyforleave',
            name='leave_type',
            field=models.TextField(max_length=100),
        ),
        migrations.AddField(
            model_name='applyforleave',
            name='leave_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.leavetable'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.leavetable'),
        ),
    ]
